### ISSUE TITLE
create wallet and send btc has 1 error 

### ISSUE THREAD

**Issue by alirayaneh** [blocktrail/blocktrail-sdk-php#52] opened 2017-01-22 15:04 UTC
when try to send btc or when try to creat wallet by api . get this error

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Negative integers not supported by Buffer::int. This could be an application error, or you should be using templates. Input was: -2147483648' in G:\wamp64\www\blocktrail\vendor\bitwasp\buffertools\src\Buffertools\Buffer.php on line 87
( ! ) InvalidArgumentException: Negative integers not supported by Buffer::int. This could be an application error, or you should be using templates. Input was: -2147483648 in G:\wamp64\www\blocktrail\vendor\bitwasp\buffertools\src\Buffertools\Buffer.php on line 87

when app call this function 
` getRedeemScriptByPath > buildKey ` 
get error 

i tink this erorr is from here
 \src\Bitcoin\BIP32Key.php
on line 148. var_dump result  for $path on line 148:
`G:\wamp64\www\blocktrail\src\Bitcoin\BIP32Key.php:148:string '0' (length=1)`
`G:\wamp64\www\blocktrail\src\Bitcoin\BIP32Key.php:148:string '16' (length=2)`
`G:\wamp64\www\blocktrail\src\Bitcoin\BIP32Key.php:148:string '0/0/16' (length=6)`
`G:\wamp64\www\blocktrail\src\Bitcoin\BIP32Key.php:148:string '0/16' (length=4)`
`G:\wamp64\www\blocktrail\src\Bitcoin\BIP32Key.php:148:string '0'/0/4' (length=6)`

**Comment by afk11** [comment] 2017-01-22 20:00
Something about your build is 32-bit, probably the PHP component installed by wamp64. How did you install the library may I ask? We added something that should prevent this, but didn't backport it, so you're probably not running one of the more recent versions?

**Comment by alirayaneh** [comment] 2017-01-22 23:00
thank you for replay 
at last  week i have copy matser source from githube and  installed  it by composer command { composer install  } from cmd .

**Comment by alirayaneh** [comment] 2017-01-23 00:01
i have test it in xamp 7 .
and get last error repeat..

**Comment by afk11** [comment] 2017-01-23 08:30
Pretty sure you're still on 32-bit. echo PHP_INT_MAX to check.

**Comment by alirayaneh** [comment] 2017-01-23 11:29
2147483647

**Comment by afk11** [comment] 2017-01-23 13:45
Ok, that's 32-bit PHP, because it equals `(pow(2, $nBits = 32) / 2) - 1` 

The error is caused by 32-bit PHP's handling of integer operations close to INT_MAX. As you can see, the number in the error is _above_ PHP_INT_MAX, which to 32-bit PHP means it's negative.

**Comment by alirayaneh** [comment] 2017-01-23 23:06
thanks alot . 
and what is best way to fix it ?

**Comment by kunalagon** [comment] 2017-02-06 10:56
use php 7

**Comment by AbdelkaderBah** [comment] 2017-03-15 20:46
Please close this issue @alirayaneh

**Closed** 2017-03-16 17:17 UTC

**Comment by LeandroVCastro** [comment] 2017-07-05 16:38
I'm with the same error. I already have change my php from 5.x.x to 7.x and the error persist.
To be more exactly my two error are:
 Fatal error: Uncaught RuntimeException: Iteration count should be at least 512 in C:\wamp64\www\blocktrail\vendor\blocktrail\blocktrail-sdk\src\V3Crypt\KeyDerivation.php on line 26

And

RuntimeException: Iteration count should be at least 512 in C:\wamp64\www\blocktrail\vendor\blocktrail\blocktrail-sdk\src\V3Crypt\KeyDerivation.php on line 26

I can auth. The error happens when i try create the wallet... 

Anybody can help-me?
